PREFIX bise: <http://bise-eu.info/core-ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX wprdf: <http://rdf.wikipathways.org/>
PREFIX prov:  <http://www.w3.org/ns/prov#>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX dc:    <http://purl.org/dc/elements/1.1/>

#id_software;id_entity;id_type;License

CONSTRUCT {

  ?entryURI a bise:Software .

}
FROM <file:softwareartifact.csv>
WHERE {

  BIND("http://bise-eu.info/data/" AS ?baseURI)

  BIND(URI(CONCAT(?baseURI,'entry/id:', ?id_entity)) AS ?entryURI)
  BIND(URI(CONCAT(?baseURI,'software/id:', ?id_software)) AS ?softwareURI)
}
