PREFIX biii: <http://biii.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX wprdf: <http://rdf.wikipathways.org/>
PREFIX prov:  <http://www.w3.org/ns/prov#>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX dc:    <http://purl.org/dc/elements/1.1/>

#id_entity ; id_user_skill ; id_curator ; id_paper ; Title ; Body ; Authors ; Training\ material ; LocationPath ; ImagePath

CONSTRUCT {

?entryURI a biii:Entry;

    rdfs:label ?Title ;
    rdfs:comment ?Body ;

    biii:hasPaper ?paperURI ;
    biii:hasCurator ?curatorURI ;
    biii:hasAuthor ?Authors ;
    biii:hasLocationPath ?LocationPath ;
    biii:hasImage ?ImagePath .

}
WHERE {
	BIND("http://biii.org/" AS ?baseURI)

  #BIND(xsd:string(?id_entity) AS ?id)
	#BIND(URI(CONCAT(?baseURI,'entry/id:', xsd:string(?id))) AS ?entryURI)
  BIND(URI(CONCAT(?baseURI,'entry/id:', ?id_entity)) AS ?entryURI)
  BIND(URI(CONCAT(?baseURI,'paper/id:', ?id_paper)) AS ?paperURI)
  BIND(URI(CONCAT(?baseURI,'curator/id:', ?id_curator)) AS ?curatorURI)
}
